### ISSUE TITLE
List unclaimed games

### ISSUE THREAD

**Issue by mainrs** [smbl64/humble-cli#17]
Would it be possible to list functionality for unclaimed games? I sometimes do not claim games and it would be nice to get an overview of what I did not claim.

A simple table that contains the game's name would be cool.

**Comment by smbl64** [comment]
Oh I see there is a `claimed` field in the response from HB. So yes, this is possible. 
I will add a new filter for it.

**Comment by smbl64** [comment]
Please check the `v0.8.0` release. Using this command should show your unclaimed games:
```
humble-cli list --claimed no
```

Personally I don't have any unclaimed bundles, so I couldn't test it with my bundles. Feel free to re-open this issue if that option didn't work for you :)  

P.S. You can install the latest version with `cargo install humble-cli` as well.

**Comment by mainrs** [comment]
It technically works. I was hoping to get a list of games that I have yet not claimed. 

As soon as a user claims a single game from a bundle, the whole bundle is marked as claimed. The Humble Choice bundle contains a selection of usually 10 games a user can choose from. 
I was hoping for a command that would list the unclaimed games inside these bundles for me.

However, the new flag is useful for single purchases as well as book bundles :) Thank you!

**Comment by smbl64** [comment]
Ah, I see.

> The Humble Choice bundle contains a selection of usually 10 games a user can choose from.

Does it mean that let's say HB gives you 10 games and you can choose 5 games out of them? And then you would like to see which of those games you have "claimed" etc?

Maybe it would be easier if I just subscribe to it for one month and do some experiments 😄

**Comment by smbl64** [comment]
I purchased Humble Choice for one month to see how it works :) 
HBC works similar to a bundle that I already owned, which has claimable keys for Manning Publication.

I _think_ I understood what you were asking for. I will work on a new version with the feature that you asked.
