### ISSUE TITLE
Thread panick?

### ISSUE THREAD

**Issue by LuckyDarms** [smbl64/humble-cli#42]
Just checking this tool out, seems very cool and useful but I seem to be having some poor luck with it. I do have a lot of bundles so I was  hoping this could help me sort through some of them and see what I have unredeemed and so on.

Running the latest version. If there is any other info you want for diagnostics just let me know.
Also, listing the humble choice for the month worked just fine.

```
C:\Users\username\Documents>humble-cli list
198 bundle(s) found.

thread 'main' panicked at src\models.rs:80:18:
expected human_name to be a string
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by smbl64** [comment]
Hi @LuckyDarms,

I just made a change which should solve that problem.
Can you please try the latest version and see if works for you (`v0.15.0`)? 🤞

**Comment by LuckyDarms** [comment]
Works great! Thank you!
