### ISSUE TITLE
Download fails with os error 3 if a part of download path has trailing char sanitized to space

### ISSUE THREAD

**Issue by topennanen** [smbl64/humble-cli#49]
(Windows) When downloading a book bundle where one of the books was named "The Best of Make:" , the download failed with os error 3.
Fixed when the replacement char at util.rs:25 was changed from space to underscore, so probable cause was trailing space in directory name which caused the subdirectory be created as "The Best of Make" but trying to use "/The Best of Make /" with the trailing space in the download path failed as the directory with that name did not exist.

**Comment by smbl64** [comment]
Hi! 

Thank you for the analysis. 
Indeed, it seems Windows ignores any whitespace as suffix.

**Comment by smbl64** [comment]
Could you please test [0.15.1](https://github.com/smbl64/humble-cli/releases/tag/v0.15.1) to see whether it downloads the bundle properly?

**Comment by topennanen** [comment]
It does work correctly now, thanks!

**Comment by smbl64** [comment]
Thank you for confirming! Will close the issue.
