### ISSUE TITLE
400 Bad request error with valid token

### ISSUE THREAD

**Issue by Monthrect** [smbl64/humble-cli#6]
Have downloaded latest version, grabbed token and put into .humble-cli-key however receiving following error:
![image](https://user-images.githubusercontent.com/16352672/184345406-a00cc3bd-2652-4dc7-94ad-3f05b0be1d86.png)

**Comment by smbl64** [comment]
Which OS are you using? 
Can you also try `humble-cli list --id-only` to see if you get any result back?

**Comment by Monthrect** [comment]
> 

Tried on both Ubuntu 20.04 & 22.04

**Comment by smbl64** [comment]
Sorry, I couldn't reproduce the issue on an Ubuntu machine.

Does this work for you? `humble-cli list --id-only`

**Comment by Monthrect** [comment]
Yup, on one machine I can see the ID's print out successfully, on the other I'm getting the following error:

`$./humblecli: error while loading shared libraries: libssl.so.1.1: cannot open share dobject file: No such file or directory`
(This is a fresh ubuntu 22.04 install)

**Comment by smbl64** [comment]
Yes, there is a problem with SSL library on newer Ubuntu versions. I will fix that in #7.

Since you can see ID's, this means the token is correct. I suspect one of the purchases is in a format that `humble-cli` cannot handle. Humble Bundle doesn't have a documented API, so I have implemented and tested this tool based on my own purchases :) 

You can find the culprit in your purchases with this command:
```
humble-cli list --id-only | xargs -I {} sh -c 'echo Bundle ID = {} && humble-cli details {}'
```

**Comment by smbl64** [comment]
I think I found the root-cause. You probably have too many bundles and that's why getting all of their info at once fails.

Just to confirm, can you tell me the output this command gives you?
```
humble-cli list --id-only | wc -l
```

**Comment by smbl64** [comment]
Hi @Monthrect. Please check the new `0.6.0` release. It should fix the SSL and `400 Bad Request` errors.

**Comment by Monthrect** [comment]
Hi @smbl64 great news, 0.6.0 is working great, except the full help file isn't printing with `--help` but other than that downloads are working.
