### ISSUE TITLE
Retrieved session key incorrect in Firefox & Chrome

### ISSUE THREAD

**Issue by JinxLuckless** [smbl64/humble-cli#62]
I usually use Firefox, and was able to easily follow the directions to get the session key in _simpleauth_sess.

However, when I tried humble-cli auth [the key], it gives me the following error:
Expressions are only allowed as the first element of a pipeline.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpressionsMustBeFirstInPipeline
    
  There are two pipes in the session key-- it's a series of numbers & letters, then a |, then just some numbers, then a |, and a group of numbers and letters. If I remove everything from the | and beyond, I don't get the error, but trying to use 'humble-cli ls' gives me the error that it's an unauthorized request, and suggests the key is wrong.

  Thinking it could be because my firefox is heavily modified by extensions, I opened a fresh Chrome browser with no add-ons, and retrieved the session key there. However, I got the exact same string I got in Firefox with the two |'s.
  
  If it helps, the first section of it is 156 characters, the middle part (without including the pipes) is 10 numbers, and the last section without the pipe is 40 characters. I've tried each of these 3 sections separately as the 'key', and humble-cli accepts them, but then says unauthorized request. And if any |'s are still in it, I get the above error about expressions.
  
  Edited because I forgot to say, I'm on Windows 10, using powershell in admin mode. I tried in cmd-prompt as well just in case, but got basically the same results.

**Comment by smbl64** [comment]
Hi @JinxLuckless .

The token format you described looks correct. My HB token is similar.

Try wrapping your token in quotes:
```
humble-cli auth '<TOKEN>'
```

**Comment by JinxLuckless** [comment]
Oh, of course! I should've realized, thank you so much. That works, thanks!

**Comment by JinxLuckless** [comment]
Wasn't a bug, my bad. Thank you for your help!
